version: '3.8'

services:
  app:
    image: factool
    container_name: factool-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - factool-network

  db:
    image: mysql:5.7
    container_name: factool-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: factool
    ports:
      - "3306:3306"
    networks:
      - factool-network

networks:
  factool-network:
    driver: bridge
